Changed the pipeline

diff --git a/.github/workflows/ecr.build.yml b/.github/workflows/ecr.build.yml
--- a/.github/workflows/ecr.build.yml
+++ b/.github/workflows/ecr.build.yml
@@ -1,54 +1,51 @@
-name: Build and Push Docker Images to ECR
-
-on:
-  push:
-    branches:
-      - main
-
-permissions:
-  id-token: write
-  contents: read
-
 jobs:
   build-and-push:
-    name: Build and Push Docker Images to ECR
-  
-
     runs-on: ubuntu-latest
 
+    permissions:
+      id-token: write
+      contents: read
+
     steps:
-
-      - name: Checkout code
-        uses: actions/checkout@v3
-
-       
+      - name: Checkout Repository
+        uses: actions/checkout@v4
 
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v4
         with:
           role-to-assume: arn:aws:iam::279715467865:role/github-ecr-oidc-role
           aws-region: ap-south-2
-      
+
       - name: Login to Amazon ECR
         id: login-ecr
         uses: aws-actions/amazon-ecr-login@v2
 
-
-      - name: Build, Tag, and Push Docker Image
+      # Build Images
+      - name: Build Backend Image
         run: |
-          docker build -t photo-gallery-backend ./backend
-          docker tag photo-gallery-backend:latest \
-          ${{ steps.login-ecr.outputs.registry }}/photo-gallery-backend:BACKENDv1
-          docker push \
-          ${{ steps.login-ecr.outputs.registry }}/photo-gallery-backend:BACKENDv1
+          docker build -t ${{ steps.login-ecr.outputs.registry }}/photo-gallery-backend:v1 ./backend
 
-
-      - name: Build, Tag, and Push Docker Image
+      - name: Build Frontend Image
         run: |
-          docker build -t photo-gallery-frontend ./frontend
-          docker tag photo-gallery-frontend:latest \
-          ${{ steps.login-ecr.outputs.registry }}/photo-gallery-frontend:FRONTENDv1
-          docker push \
-          ${{ steps.login-ecr.outputs.registry }}/photo-gallery-frontend:v1
+          docker build -t ${{ steps.login-ecr.outputs.registry }}/photo-gallery-frontend:v1 ./frontend
 
+      # Push Images
+      - name: Push Backend Image
+        run: |
+          docker push ${{ steps.login-ecr.outputs.registry }}/photo-gallery-backend:v2
 
+      - name: Push Frontend Image
+        run: |
+          docker push ${{ steps.login-ecr.outputs.registry }}/photo-gallery-frontend:v2
+
+      # Cleanup if anything failed
+      - name: Cleanup ECR Images
+        if: failure()
+        run: |
+          aws ecr batch-delete-image \
+            --repository-name photo-gallery-backend \
+            --image-ids imageTag=v1 || true
+
+          aws ecr batch-delete-image \
+            --repository-name photo-gallery-frontend \
+            --image-ids imageTag=v1 || true
